#!/bin/bash
#
# Replay Historical Claude Code Sessions
#
# Imports complete conversation history into claude-mem database:
# - All user messages (searchable)
# - Observations from tool usage (generated by SDK)
# - Session summaries
#
# Usage:
#   ./scripts/replay-history.sh                    # Replay all projects
#   ./scripts/replay-history.sh <project-dir>      # Replay single project
#   ./scripts/replay-history.sh --dry-run          # Preview without importing
#

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Check prerequisites
if [ ! -f "$PROJECT_ROOT/package.json" ]; then
  echo -e "${RED}❌ Error: Must run from claude-mem project directory${NC}"
  exit 1
fi

if ! command -v npx &> /dev/null; then
  echo -e "${RED}❌ Error: npx not found${NC}"
  exit 1
fi

# Check if worker is running
WORKER_PORT=37777
if ! curl -s http://127.0.0.1:$WORKER_PORT/api/health > /dev/null 2>&1; then
  echo -e "${RED}❌ Error: Worker service not running${NC}"
  echo "Start it with: npm run worker:start"
  exit 1
fi

echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║${NC}  Claude-Mem History Replay"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "This will import complete conversation history into claude-mem:"
echo "  ✓ All user messages"
echo "  ✓ Observations from tool usage (generated by SDK)"
echo "  ✓ Session summaries"
echo ""

cd "$PROJECT_ROOT"

# Pass all arguments to the TypeScript script
npx tsx src/bin/replay-history.ts "$@"

EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
  echo ""
  echo -e "${GREEN}✓ History replay complete!${NC}"
  echo ""
  echo "View results:"
  echo "  Web UI: http://localhost:37777"
  echo "  Logs: npm run worker:logs"
fi

exit $EXIT_CODE

